### ISSUE TITLE
generate encrypt.txt failed

### ISSUE THREAD

**Issue by angeliababy** [allenlee820202/Parallel-AES-Algorithm-using-CUDA#2]
when input.txt is too large(>20000 line),AES_encrypt kernel do not run,the results is incorrect.please help me

**Comment by allenlee820202** [comment]
Sorry that I don't have CUDA environment now and cannot do test for you. I guessed your input lines are too much that reaches the memory limitation of GPU itself. See this line:
```
cudaMalloc(&cuda_aes_block_array, block_number*sizeof(class aes_block));
```
Maybe you can try to separate the input lines and do several rounds of cudaMalloc, cudaMemcpy, AES_Encrypt, cudaMemcpy. Then concatenate the results instead of doing it with just one round of these operations.

Hope this help!

**Comment by angeliababy** [comment]
Thank you. I've settled it. refer to this website：https://blog.csdn.net/moonboat0331/article/details/10589815.
set --maxrregcount =24 at compile time
